services:
  lnkphm-portfolio:
    container_name: lnkphm-portfolio
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      - lnkphm-portfolio

networks:
  lnkphm-portfolio:
    external: true
