services:
  lnkphm-portfolio-dev:
    container_name: lnkphm-portfolio-dev
    build:
      context: ./
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: always
    ports:
      - 3000:3000
    networks:
      - lnkphm-portfolio-dev

networks:
  lnkphm-portfolio-dev:
    external: true
