services:
  lnkphm-portfolio-dev:
    container_name: lnkphm-portfolio-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: always
    ports:
      - 3000:3000
    networks:
      - portfolio

networks:
  portfolio:
